In [7]:
import pandas as pd
df = pd.read_csv('advertising_simple.csv')
print(df)

    TV  Radio  Newspaper  Sales
0   44     39         45     10
1   17     45         69     12
2  151     41         58     16
3  180     10         58     17
4    8     48         75      7
5   57     32         23     11
6  120     19         11     13
7    8      2          1      4

In [8]:
print(df.describe())

               TV      Radio  Newspaper      Sales
count    8.000000   8.000000   8.000000   8.000000
mean    73.125000  29.500000  42.500000  11.250000
std     68.059716  17.146428  27.619869   4.334249
min      8.000000   2.000000   1.000000   4.000000
25%     14.750000  16.750000  20.000000   9.250000
50%     50.500000  35.500000  51.500000  11.500000
75%    127.750000  42.000000  60.750000  13.750000
max    180.000000  48.000000  75.000000  17.000000

In [9]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         8 non-null      int64
 1   Radio      8 non-null      int64
 2   Newspaper  8 non-null      int64
 3   Sales      8 non-null      int64
dtypes: int64(4)
memory usage: 388.0 bytes
None

In [24]:
df.sort_values(['Newspaper', 'Radio'], ascending = [True, True])

    TV  Radio  Newspaper  Sales
7    8      2          1      4
6  120     19         11     13
5   57     32         23     11
0   44     39         45     10
3  180     10         58     17
2  151     41         58     16
1   17     45         69     12
4    8     48         75      7

In [39]:
df

     TV  Radio  Newspaper  Sales
ID
1   180     10         58     17
2   151     41         58     16
3   120     19         11     13
4    17     45         69     12
5    57     32         23     11
6    44     39         45     10
7     8     48         75      7
8     8      2          1      4

In [37]:
df['ID'] = [1, 2, 3, 4, 5, 6, 7, 8]

In [38]:
df.set_index('ID', inplace=True)

In [42]:
df = df.reset_index(drop=True, inplace=False) #neu inplace = True: no thuc hien tai bo nho, khong can gan lai
df

    TV  Radio  Newspaper  Sales  Values
0  180     10         58     17       1
1  151     41         58     16       2
2  120     19         11     13       3
3   17     45         69     12      40
4   57     32         23     11       5
5   44     39         45     10       6
6    8     48         75      7       7
7    8      2          1      4       8

In [41]:
df['Values'] = [1, 2, 3, 40, 5, 6, 7, 8]
df

    TV  Radio  Newspaper  Sales  Values
0  180     10         58     17       1
1  151     41         58     16       2
2  120     19         11     13       3
3   17     45         69     12      40
4   57     32         23     11       5
5   44     39         45     10       6
6    8     48         75      7       7
7    8      2          1      4       8

In [10]:
df_t = df.T
print(df_t)

            0   1    2    3   4   5    6  7
TV         44  17  151  180   8  57  120  8
Radio      39  45   41   10  48  32   19  2
Newspaper  45  69   58   58  75  23   11  1
Sales      10  12   16   17   7  11   13  4