In [26]:
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
df = pd.read_csv('WeatherHistory2D.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Formatted Date   96453 non-null  str
 1   Temperature (C)  96453 non-null  float64
dtypes: float64(1), str(1)
memory usage: 1.5 MB

In [27]:
df

                      Formatted Date  Temperature (C)
0      2006-01-01 00:00:00.000 +0100         0.577778
1      2006-01-01 01:00:00.000 +0100         1.161111
2      2006-01-01 02:00:00.000 +0100         1.666667
3      2006-01-01 03:00:00.000 +0100         1.711111
4      2006-01-01 04:00:00.000 +0100         1.183333
...                              ...              ...
96448  2016-12-31 19:00:00.000 +0100         0.488889
96449  2016-12-31 20:00:00.000 +0100         0.072222
96450  2016-12-31 21:00:00.000 +0100        -0.233333
96451  2016-12-31 22:00:00.000 +0100        -0.472222
96452  2016-12-31 23:00:00.000 +0100        -0.677778

[96453 rows x 2 columns]

In [28]:
datetime = pd.to_datetime('2006-12-01 00:00:00 +0100', utc=True)
print(datetime)
print(datetime.year)
print(datetime.month)
print(datetime.day)
print(datetime.hour)

2006-11-30 23:00:00+00:00
2006
11
30
23

In [29]:
df['Formatted Date'] = pd.to_datetime(df['Formatted Date'], utc=True)
df

                 Formatted Date  Temperature (C)
0     2005-12-31 23:00:00+00:00         0.577778
1     2006-01-01 00:00:00+00:00         1.161111
2     2006-01-01 01:00:00+00:00         1.666667
3     2006-01-01 02:00:00+00:00         1.711111
4     2006-01-01 03:00:00+00:00         1.183333
...                         ...              ...
96448 2016-12-31 18:00:00+00:00         0.488889
96449 2016-12-31 19:00:00+00:00         0.072222
96450 2016-12-31 20:00:00+00:00        -0.233333
96451 2016-12-31 21:00:00+00:00        -0.472222
96452 2016-12-31 22:00:00+00:00        -0.677778

[96453 rows x 2 columns]

In [30]:
df['Year'] = df['Formatted Date'].dt.year
df['Month'] = df['Formatted Date'].dt.month
df['Day'] = df['Formatted Date'].dt.day
df['Hour'] = df['Formatted Date'].dt.hour
df

                 Formatted Date  Temperature (C)  Year  Month  Day  Hour
0     2005-12-31 23:00:00+00:00         0.577778  2005     12   31    23
1     2006-01-01 00:00:00+00:00         1.161111  2006      1    1     0
2     2006-01-01 01:00:00+00:00         1.666667  2006      1    1     1
3     2006-01-01 02:00:00+00:00         1.711111  2006      1    1     2
4     2006-01-01 03:00:00+00:00         1.183333  2006      1    1     3
...                         ...              ...   ...    ...  ...   ...
96448 2016-12-31 18:00:00+00:00         0.488889  2016     12   31    18
96449 2016-12-31 19:00:00+00:00         0.072222  2016     12   31    19
96450 2016-12-31 20:00:00+00:00        -0.233333  2016     12   31    20
96451 2016-12-31 21:00:00+00:00        -0.472222  2016     12   31    21
96452 2016-12-31 22:00:00+00:00        -0.677778  2016     12   31    22

[96453 rows x 6 columns]

In [ ]:
df.drop('Formatted Date', axis = 1, inplace=True)
df

       Temperature (C)  Year  Month  Day  Hour
0             0.577778  2005     12   31    23
1             1.161111  2006      1    1     0
2             1.666667  2006      1    1     1
3             1.711111  2006      1    1     2
4             1.183333  2006      1    1     3
...                ...   ...    ...  ...   ...
96448         0.488889  2016     12   31    18
96449         0.072222  2016     12   31    19
96450        -0.233333  2016     12   31    20
96451        -0.472222  2016     12   31    21
96452        -0.677778  2016     12   31    22

[96453 rows x 5 columns]

In [36]:
df.drop(['Year', 'Month'], axis = 1)

       Temperature (C)  Day  Hour
0             0.577778   31    23
1             1.161111    1     0
2             1.666667    1     1
3             1.711111    1     2
4             1.183333    1     3
...                ...  ...   ...
96448         0.488889   31    18
96449         0.072222   31    19
96450        -0.233333   31    20
96451        -0.472222   31    21
96452        -0.677778   31    22

[96453 rows x 3 columns]

In [43]:
df.drop([1, 2], axis = 0)

       Temperature (C)  Year  Month  Day  Hour
0             0.577778  2005     12   31    23
3             1.711111  2006      1    1     2
4             1.183333  2006      1    1     3
5             1.205556  2006      1    1     4
6             2.222222  2006      1    1     5
...                ...   ...    ...  ...   ...
96448         0.488889  2016     12   31    18
96449         0.072222  2016     12   31    19
96450        -0.233333  2016     12   31    20
96451        -0.472222  2016     12   31    21
96452        -0.677778  2016     12   31    22

[96451 rows x 5 columns]