In [248]:
import pandas as pd
data = {
    'Name': ['A', 'B', 'C', 'D'],
    'Gender': ['M', 'F', 'F', 'M']
}
data_frame = pd.DataFrame(data)

print(type(data_frame))

<class 'pandas.DataFrame'>

In [249]:
data_frame

  Name Gender
0    A      M
1    B      F
2    C      F
3    D      M

In [250]:
name_series = data_frame['Name']
print(type(name_series))

<class 'pandas.Series'>

In [251]:
name_series

0    A
1    B
2    C
3    D
Name: Name, dtype: str

In [252]:
gender_series = data_frame['Gender']
print(type(gender_series))

<class 'pandas.Series'>

In [253]:
gender_series

0    M
1    F
2    F
3    M
Name: Gender, dtype: str

In [254]:
new_df = pd.concat(
    [name_series, gender_series], axis = 1
)
print(type(new_df))

<class 'pandas.DataFrame'>

In [255]:
new_df

  Name Gender
0    A      M
1    B      F
2    C      F
3    D      M

In [256]:
import xarray as xr
data_1 = {
    'Name': ['A', 'B', 'C', 'D'],
    'Gender': ['M', 'F', 'F', 'M']
}
data_2 = {
    'Name': ['E', 'F', 'G', 'H', 'I'],
    'Gender': ['M', 'M', 'F', 'F', 'M']
}

df1 = pd.DataFrame(data_1).to_xarray()
df2 = pd.DataFrame(data_2).to_xarray()

panel_data = xr.concat(
    [df1, df2], dim = 'panel_dim'
)
panel_data

/var/folders/dj/wq5m3k51329gtd7_lpqdxj5m0000gn/T/ipykernel_83293/1022771945.py:14: FutureWarning: In a future version of xarray the default value for join will change from join='outer' to join='exact'. This change will result in the following ValueError: cannot be aligned with join='exact' because index/labels/sizes are not equal along these coordinates (dimensions): 'index' ('index',) The recommendation is to set join explicitly for this case.
  panel_data = xr.concat(

<xarray.Dataset> Size: 200B
Dimensions:  (panel_dim: 2, index: 5)
Coordinates:
  * index    (index) int64 40B 0 1 2 3 4
Dimensions without coordinates: panel_dim
Data variables:
    Name     (panel_dim, index) object 80B 'A' 'B' 'C' 'D' ... 'F' 'G' 'H' 'I'
    Gender   (panel_dim, index) object 80B 'M' 'F' 'F' 'M' ... 'M' 'F' 'F' 'M'

In [257]:
import numpy as np
DATASET_PATH = '../data/Pokemon.csv'
data = pd.read_csv(DATASET_PATH)

data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [258]:
data.to_csv('modified.csv')

data.to_excel('modified.xlsx', index = False)

data.to_csv('modified_tab.csv', sep = '\t')

In [259]:
data.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [260]:
data.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [261]:
data.tail(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [262]:
data.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='str')

In [263]:
data[['Name', 'HP']]

                      Name  HP
0                Bulbasaur  45
1                  Ivysaur  60
2                 Venusaur  80
3    VenusaurMega Venusaur  80
4               Charmander  39
..                     ...  ..
795                Diancie  50
796    DiancieMega Diancie  50
797    HoopaHoopa Confined  80
798     HoopaHoopa Unbound  80
799              Volcanion  80

[800 rows x 2 columns]

In [264]:
data[['Name', 'Total', 'Attack']][:10:2]

                        Name  Total  Attack
0                  Bulbasaur    318      49
2                   Venusaur    525      82
4                 Charmander    309      52
6                  Charizard    534      84
8  CharizardMega Charizard Y    634     104

In [265]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [266]:
data = data.drop(columns = ['Total'])
data.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [267]:
data['Total'] = data['Attack'] + data['Defense'] + data['HP']
data.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134

In [268]:
cols = list(data.columns.values)
print(cols)

['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total']

In [269]:
data[cols[0:4] + [cols[-1]] + cols[4:-1]]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,143,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,185,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,245,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,303,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,134,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,300,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,320,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,250,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,300,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,310,80,110,120,130,90,70,6,True

In [270]:
data.iloc[[3, 6, 9]]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,240
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False,157

In [271]:
data.iloc[3:9]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,180
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,240
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,319
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,260

In [272]:
data.loc[data['Legendary'] == True].head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
156,144,Articuno,Ice,Flying,90,85,100,95,125,85,1,True,275
157,145,Zapdos,Electric,Flying,90,90,85,125,90,100,1,True,265
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True,280
162,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True,306
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True,396

In [273]:
data.loc[data['Attack'] >= 180].loc[data['Legendary'] == True]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True,396
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True,440
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True,385
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True,250

In [274]:
data.loc[data['Attack'] >= 49, ['Name', 'Type 2']]

                      Name  Type 2
0                Bulbasaur  Poison
1                  Ivysaur  Poison
2                 Venusaur  Poison
3    VenusaurMega Venusaur  Poison
4               Charmander     NaN
..                     ...     ...
795                Diancie   Fairy
796    DiancieMega Diancie   Fairy
797    HoopaHoopa Confined   Ghost
798     HoopaHoopa Unbound    Dark
799              Volcanion   Water

[670 rows x 2 columns]

In [275]:
data.loc[(data['Type 1'] == 'Grass') & (data['Type 2'] == 'Poison')].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245

In [276]:
data.loc[(data['Type 1'] == 'Grass') | (data['Type 2'] == 'Poison')][0::10].loc[data['HP'] > 50].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,240
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,185
197,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,250

In [277]:
data.loc[data['Name'].str.contains('Mega')].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,319
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,260

In [278]:
data.loc[data['Type 1'].str.contains('Fire|grass', regex=True, case = False)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,143
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,185
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,245
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,303
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,134
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,170
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,226
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,179
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,285
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,310

In [279]:
import re

data.loc[data['Name'].str.contains('pi[a-z]*', flags=re.I, regex = True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False,110
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,125
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,178
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,238
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,243
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,130
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False,119
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False,205
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False,235
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False,290
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,340
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False,140
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,75
189,175,Togepi,Fairy,NaN,35,20,65,40,65,20,2,False,120
202,187,Hoppip,Grass,Flying,35,35,40,35,55,50,2,False,110
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,205
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,280
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False,224
345,316,Gulpin,Poison,NaN,70,43,53,43,53,40,3,False,166
357,326,Grumpig,Psychic,NaN,80,45,65,90,110,80,3,False,190
358,327,Spinda,Normal,NaN,60,60,60,60,60,60,3,False,180
359,328,Trapinch,Ground,NaN,45,100,45,45,45,10,3,False,190
390,357,Tropius,Grass,Flying,99,68,83,72,87,51,3,False,250
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False,157
463,416,Vespiquen,Bug,Flying,70,80,102,80,102,40,4,False,252
488,440,Happiny,Normal,NaN,100,5,5,15,65,30,4,False,110
490,442,Spiritomb,Ghost,Dark,50,92,108,92,108,35,4,False,250
501,451,Skorupi,Poison,Bug,40,50,90,30,55,65,4,False,180
502,452,Drapion,Poison,Dark,70,90,110,60,75,95,4,False,270
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False,173
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,238
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,155
596,536,Palpitoad,Water,Ground,75,65,55,65,55,69,5,False,195
716,648,MeloettaPirouette Forme,Normal,Fighting,100,128,90,77,77,128,5,False,318
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False,182

In [280]:
data.loc[data['Name'].str.contains('^pi[a-z]*', flags = re.I, regex = True)].head(3)

#flags = re.I : Ignorecase => dung de phan biet chu hoa, neu = True thi khong xet viet hoa hay thuong

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,125
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,178
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,238

In [281]:
data.loc[data['Name'].str.contains('^pi.*', flags = re.I, regex = True)].head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,125
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,178
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,238

In [282]:
data.loc[data['Name'].str.contains('^pi[abc]', flags = re.I, regex = True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,75

In [283]:
data.sort_values('HP', ascending = False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False,275
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False,260
217,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False,281
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False,305
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False,85
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False,55
388,355,Duskull,Ghost,NaN,20,40,90,30,90,25,3,False,150
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False,90
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False,136

In [284]:
data.sort_values(['HP', 'Attack', 'Type 2'], ascending = [True, False, True])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False,136
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False,90
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,75
388,355,Duskull,Ghost,NaN,20,40,90,30,90,25,3,False,150
487,439,Mime Jr.,Psychic,Fairy,20,25,45,70,90,60,4,False,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False,320
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False,305
217,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False,281
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False,260
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False,275

In [291]:
new_data = data.loc[(data['Type 1'] == 'Grass') | (data['Type 2'] == 'Poison')][0::10].loc[data['HP'] > 50].head(3)
new_data

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,240
101,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,185
197,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,250

In [ ]:
new_data.reset_index(drop = True, inplace = True) #khong can gan lai
new_data

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,240
1,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False,185
2,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,250

In [300]:
data.groupby('Type 1')[['Defense']].mean().sort_values('Defense', ascending = False).head(10)

           Defense
Type 1
Steel   126.370370
Rock    100.795455
Dragon   86.375000
Ground   84.843750
Ghost    81.187500
Water    72.946429
Ice      71.416667
Grass    70.800000
Bug      70.724638
Dark     70.225806

In [ ]:
df = data.groupby(['Type 1']).agg({
    'Attack': 'mean',
    'Defense': 'sum',
    'Speed': lambda x : len(x) #Dem so dong
})
df.head(10)

              Attack  Defense  Speed
Type 1
Bug        70.971014     4880     69
Dark       88.387097     2177     31
Dragon    112.125000     2764     32
Electric   69.090909     2917     44
Fairy      61.529412     1117     17
Fighting   96.777778     1780     27
Fire       84.769231     3524     52
Flying     78.750000      265      4
Ghost      73.781250     2598     32
Grass      73.214286     4956     70

In [307]:
df = data.groupby('Type 1')[['HP', 'Attack']].mean()
df

                 HP      Attack
Type 1
Bug       56.884058   70.971014
Dark      66.806452   88.387097
Dragon    83.312500  112.125000
Electric  59.795455   69.090909
Fairy     74.117647   61.529412
Fighting  69.851852   96.777778
Fire      69.903846   84.769231
Flying    70.750000   78.750000
Ghost     64.437500   73.781250
Grass     67.271429   73.214286
Ground    73.781250   95.750000
Ice       72.000000   72.750000
Normal    77.275510   73.469388
Poison    67.250000   74.678571
Psychic   70.631579   71.456140
Rock      65.363636   92.863636
Steel     65.222222   92.703704
Water     72.062500   74.151786