In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('weatherHistory_simple.csv')
df

  Precip Type  Temperature (C)
0        rain             12.2
1        rain             13.8
2        rain             14.7
3        rain             13.8
4        rain             12.7
5        rain              0.5
6        snow             -0.4
7        snow             -1.1
8        snow             -1.6
9        snow             -2.1

In [12]:
type(df.groupby('Precip Type').size())

pandas.Series

In [17]:
df['Temperature (F)'] = df['Temperature (C)'] * 9 / 5 + 32

In [18]:
df

  Precip Type  Temperature (C)  Temperature (F)
0        rain             12.2            53.96
1        rain             13.8            56.84
2        rain             14.7            58.46
3        rain             13.8            56.84
4        rain             12.7            54.86
5        rain              0.5            32.90
6        snow             -0.4            31.28
7        snow             -1.1            30.02
8        snow             -1.6            29.12
9        snow             -2.1            28.22